[package]
name = "hyper_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.33"
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = "0.9.27"
hyper = { version = "1.0", features = ["full"] }

# [target.wasm32-wasi.dependencies]
# hyper_wasi = "0.15.2"

# [target.x86_64-unknown-linux-gnu.dependencies]

[dev-dependencies]
serde_qs = "0.12.0"
tokio = { version = "1.34.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
body = "0.1.1"
