[package]
name = "hyper_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
hyper = { version = "0.14.24", features = ["full"] }
quote = "1.0.23"

[target.wasm32-wasi.dependencies]
hyper_wasi = "0.15.1"

[target.x86_64-unknown-linux-gnu.dependencies]
hyper = "0.14.24"
