[package]
name = "hyper_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
hyper = { version = "0.14.26", features = ["full"] }
hyper_serde = "0.13.0"
proc-macro2 = "1.0.52"
quote = "1.0.28"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"

[target.wasm32-wasi.dependencies]
hyper_wasi = "0.15.1"

[target.x86_64-unknown-linux-gnu.dependencies]
hyper = "0.14.26"
